#!/usr/bin/env python3
"""
BG Jobs - Professional Govt Job Portal Builder
GitHub Pages Build Script with Dark/Light Mode Support
"""

import os
import json
import shutil
from datetime import datetime
from pathlib import Path

# ============================================================
# CONFIGURATION
# ============================================================

SITE_NAME = "BG Jobs"
SITE_URL = "https://bgsarkariresult.github.io/bgjob/"
SITE_DESCRIPTION = "Professional Government Job Portal - Latest Jobs, Admit Cards, Results, Syllabus & Books"
SITE_KEYWORDS = "Sarkari Result, BG Jobs, MPESB Patwari, Bank Jobs, SSC CGL 2026, Railway Recruitment, Admit Card, Results 2026, Govt Jobs, Books"
SITE_AUTHOR = "BG Jobs"
THEME_COLOR_LIGHT = "#ffffff"
THEME_COLOR_DARK = "#0a0a0a"

# Directory structure
BUILD_DIR = Path("_build")
ASSETS_DIR = Path("assets")
CSS_DIR = ASSETS_DIR / "css"
JS_DIR = ASSETS_DIR / "js"
IMAGES_DIR = ASSETS_DIR / "images"

# ============================================================
# DIRECTORY SETUP
# ============================================================

def setup_directories():
    """Create necessary directory structure"""
    directories = [
        BUILD_DIR,
        BUILD_DIR / "jobs",
        BUILD_DIR / "results",
        BUILD_DIR / "admit-card",
        BUILD_DIR / "answer-key",
        BUILD_DIR / "syllabus",
        BUILD_DIR / "books",
        BUILD_DIR / "assets" / "css",
        BUILD_DIR / "assets" / "js",
        BUILD_DIR / "assets" / "images",
    ]
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
    print("✅ Directories created successfully")

# ============================================================
# CSS GENERATION
# ============================================================

def generate_css():
    """Generate the complete CSS file with dark/light mode support"""
    css_content = """/* BG Jobs - Professional Stylesheet with Dark/Light Mode */
/* Generated by build.py */

/* ========== CSS VARIABLES - LIGHT MODE (Default) ========== */
:root {
    --bg-primary: #ffffff;
    --bg-secondary: #f5f5f5;
    --bg-card: #ffffff;
    --text-primary: #1a1a1a;
    --text-secondary: #555555;
    --border-color: #e0e0e0;
    --ticker-bg: #ffffff;
    --ticker-text: #1a1a1a;
    --card-border: #e8e8e8;
    --card-shadow: 0 8px 24px rgba(0,0,0,0.06);
    --hover-shadow: 0 18px 32px rgba(255,107,0,0.12);
    --job-link-color: #1a1a1a;
    --job-link-hover: #ff6b00;
    --badge-new-bg: #e8f5e9;
    --badge-new-text: #1b5e20;
    --badge-new-border: #4caf50;
    --badge-hot-bg: #ffebee;
    --badge-hot-text: #b71c1c;
    --badge-hot-border: #ef5350;
    --orange-primary: #ff6b00;
    --orange-hover: #ff8533;
    --header-bg: #0d0d0d;
    --header-text: #ffffff;
    --nav-bg: #111111;
    --nav-link: #cccccc;
    --nav-active-bg: #ff6b00;
    --nav-active-text: #0a0a0a;
}

/* ========== DARK MODE ========== */
body.dark-mode {
    --bg-primary: #0a0a0a;
    --bg-secondary: #0f0f0f;
    --bg-card: #141414;
    --text-primary: #e0e0e0;
    --text-secondary: #aaaaaa;
    --border-color: #2a2a2a;
    --ticker-bg: #1a1a1a;
    --ticker-text: #dddddd;
    --card-border: #2a2a2a;
    --card-shadow: 0 8px 24px rgba(0,0,0,0.7);
    --hover-shadow: 0 18px 32px rgba(255,107,0,0.2);
    --job-link-color: #f0f0f0;
    --job-link-hover: #ff6b00;
    --badge-new-bg: #1b3a1b;
    --badge-new-text: #a5d6a7;
    --badge-new-border: #4caf50;
    --badge-hot-bg: #3a1b1b;
    --badge-hot-text: #ef9a9a;
    --badge-hot-border: #ef5350;
}

/* ========== RESET & BASE ========== */
*,
*::before,
*::after {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

html {
    scroll-behavior: smooth;
}

body {
    font-family: 'Inter', 'Segoe UI', Roboto, 'Helvetica Neue', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
    background: var(--bg-primary);
    color: var(--text-primary);
    line-height: 1.6;
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    transition: background 0.35s ease, color 0.35s ease;
}

.container {
    max-width: 1300px;
    margin: 0 auto;
    padding: 0 24px;
    width: 100%;
}

a {
    text-decoration: none;
    color: inherit;
}

ul {
    list-style: none;
}

/* ========== HEADER (Always Dark) ========== */
.site-header {
    background: var(--header-bg);
    border-bottom: 2px solid var(--orange-primary);
    box-shadow: 0 8px 24px rgba(0,0,0,0.3);
    position: sticky;
    top: 0;
    z-index: 1000;
}

.header-top {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: space-between;
    padding: 16px 24px;
    gap: 16px;
}

.header-left {
    display: flex;
    align-items: center;
    gap: 16px;
    flex-wrap: wrap;
}

.logo {
    display: flex;
    align-items: baseline;
}

.logo a {
    font-size: 2.2rem;
    font-weight: 800;
    text-decoration: none;
    letter-spacing: -0.5px;
    color: var(--header-text);
    display: flex;
    align-items: baseline;
    gap: 4px;
}

.logo span {
    background: var(--orange-primary);
    color: #0a0a0a;
    padding: 4px 16px;
    border-radius: 40px;
    font-size: 1.7rem;
    font-weight: 800;
    margin-left: 4px;
}

/* ========== MODE TOGGLE BUTTON ========== */
.mode-toggle {
    background: var(--orange-primary);
    border: 2px solid var(--orange-primary);
    color: #0a0a0a;
    font-size: 1rem;
    padding: 10px 18px;
    border-radius: 50px;
    cursor: pointer;
    font-weight: 700;
    transition: all 0.3s ease;
    white-space: nowrap;
    display: flex;
    align-items: center;
    gap: 6px;
    letter-spacing: 0.3px;
}

.mode-toggle:hover {
    background: var(--orange-hover);
    border-color: var(--orange-hover);
    box-shadow: 0 4px 16px rgba(255,107,0,0.4);
}

.mode-toggle .icon {
    font-size: 1.2rem;
}

/* ========== SEARCH BOX ========== */
.search-box {
    display: flex;
    align-items: center;
    background: #1a1a1a;
    border-radius: 50px;
    padding: 4px 6px 4px 22px;
    box-shadow: 0 4px 16px rgba(255, 107, 0, 0.15);
    min-width: 300px;
    border: 1px solid #333;
}

.search-box input {
    border: none;
    outline: none;
    font-size: 1rem;
    width: 100%;
    background: transparent;
    color: #ffffff;
}

.search-box input::placeholder {
    color: #999;
}

.search-box button {
    background: var(--orange-primary);
    border: none;
    color: #0a0a0a;
    font-size: 1.2rem;
    padding: 12px 18px;
    border-radius: 40px;
    cursor: pointer;
    transition: 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
}

.search-box button:hover {
    background: var(--orange-hover);
}

/* ========== NAVIGATION ========== */
.main-nav {
    background: var(--nav-bg);
    border-top: 1px solid #222;
}

.nav-links {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    padding: 14px 24px;
}

.nav-links a {
    color: var(--nav-link);
    text-decoration: none;
    font-weight: 600;
    font-size: 0.95rem;
    padding: 10px 22px;
    border-radius: 30px;
    transition: all 0.25s;
}

.nav-links a.active,
.nav-links a:hover {
    background: var(--nav-active-bg);
    color: var(--nav-active-text);
    box-shadow: 0 4px 16px rgba(255, 107, 0, 0.5);
    font-weight: 700;
}

/* ========== TICKER ========== */
.ticker-wrapper {
    background: var(--ticker-bg);
    border-bottom: 1px solid var(--border-color);
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    overflow: hidden;
    transition: background 0.35s ease;
}

.ticker-flex {
    display: flex;
    align-items: center;
    gap: 20px;
    padding: 14px 24px;
    white-space: nowrap;
}

.ticker-label {
    background: #ff3b30;
    color: white;
    font-weight: 700;
    padding: 8px 22px;
    border-radius: 30px;
    font-size: 0.85rem;
    white-space: nowrap;
    letter-spacing: 0.5px;
    flex-shrink: 0;
    z-index: 2;
    box-shadow: 0 4px 12px rgba(255,59,48,0.3);
}

.ticker-scroll-container {
    flex: 1;
    overflow: hidden;
    position: relative;
}

.ticker-content {
    display: flex;
    gap: 40px;
    animation: scrollTicker 25s linear infinite;
    width: max-content;
}

.ticker-content a {
    color: var(--ticker-text);
    text-decoration: none;
    font-weight: 700;
    transition: 0.2s;
    font-size: 0.98rem;
}

.ticker-content a:hover {
    color: var(--orange-primary);
    text-decoration: underline;
}

.ticker-separator {
    color: #cccccc;
    font-weight: 400;
}

@keyframes scrollTicker {
    0% { transform: translateX(0); }
    100% { transform: translateX(-50%); }
}

/* ========== MAIN CONTENT ========== */
main {
    flex: 1;
    padding: 36px 0 48px;
    background: var(--bg-secondary);
    transition: background 0.35s ease;
}

.section-title {
    text-align: center;
    margin-bottom: 28px;
    font-size: 1.8rem;
    font-weight: 800;
    color: var(--text-primary);
}

.section-title span {
    color: var(--orange-primary);
}

/* ========== JOB CARDS GRID ========== */
.job-grid-container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 28px;
}

.job-card-box {
    background: var(--bg-card);
    border-radius: 20px;
    box-shadow: var(--card-shadow);
    overflow: hidden;
    transition: transform 0.25s ease, box-shadow 0.25s ease, background 0.35s ease, border-color 0.25s;
    border: 1px solid var(--card-border);
}

.job-card-box:hover {
    transform: translateY(-6px);
    box-shadow: var(--hover-shadow);
    border-color: var(--orange-primary);
}

.box-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 18px 24px;
    color: white;
    font-weight: 700;
}

.box-header h2 {
    font-size: 1.3rem;
    display: flex;
    align-items: center;
    gap: 10px;
}

.box-header a {
    color: white;
    background: rgba(255,255,255,0.18);
    padding: 6px 16px;
    border-radius: 30px;
    text-decoration: none;
    font-size: 0.8rem;
    font-weight: 600;
    backdrop-filter: blur(4px);
    transition: 0.2s;
}

.box-header a:hover {
    background: rgba(255,255,255,0.35);
}

.bg-green {
    background: linear-gradient(135deg, #1b5e20, #2e7d32);
    border-bottom: 2px solid var(--orange-primary);
}

.bg-blue {
    background: linear-gradient(135deg, #0d47a1, #1565c0);
    border-bottom: 2px solid var(--orange-primary);
}

.bg-red {
    background: linear-gradient(135deg, #b71c1c, #c62828);
    border-bottom: 2px solid var(--orange-primary);
}

.bg-purple {
    background: linear-gradient(135deg, #4a148c, #6a1b9a);
    border-bottom: 2px solid var(--orange-primary);
}

.job-list {
    list-style: none;
    padding: 18px 24px 24px;
    display: flex;
    flex-direction: column;
    gap: 18px;
}

.job-list li {
    border-bottom: 1px solid var(--border-color);
    padding-bottom: 14px;
    transition: border-color 0.35s ease;
}

.job-list li:last-child {
    border-bottom: none;
    padding-bottom: 0;
}

.job-list a {
    text-decoration: none;
    font-weight: 600;
    color: var(--job-link-color);
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    font-size: 0.96rem;
    transition: color 0.2s;
}

.job-list a:hover {
    color: var(--job-link-hover);
}

/* ========== BADGES ========== */
.badge {
    font-size: 0.7rem;
    font-weight: 700;
    padding: 5px 12px;
    border-radius: 30px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    white-space: nowrap;
    flex-shrink: 0;
}

.badge.new {
    background: var(--badge-new-bg);
    color: var(--badge-new-text);
    border: 1px solid var(--badge-new-border);
}

.badge.hot {
    background: var(--badge-hot-bg);
    color: var(--badge-hot-text);
    border: 1px solid var(--badge-hot-border);
}

/* ========== FOOTER ========== */
.site-footer {
    background: #0d0d0d;
    color: #aaaaaa;
    text-align: center;
    padding: 28px 24px;
    border-top: 3px solid var(--orange-primary);
}

.footer-content p {
    font-size: 0.95rem;
    letter-spacing: 0.3px;
}

/* ========== RESPONSIVE ========== */
@media (max-width: 768px) {
    .header-top {
        flex-direction: column;
        align-items: flex-start;
    }
    .header-left {
        width: 100%;
        justify-content: space-between;
    }
    .search-box {
        width: 100%;
        min-width: auto;
    }
    .nav-links {
        justify-content: center;
    }
    .job-grid-container {
        grid-template-columns: 1fr;
        padding: 0 8px;
    }
}

@media (max-width: 480px) {
    .logo a {
        font-size: 1.8rem;
    }
    .logo span {
        font-size: 1.4rem;
        padding: 3px 12px;
    }
    .mode-toggle {
        font-size: 0.85rem;
        padding: 8px 14px;
    }
}

/* ========== SAFARI / APPLE FIX ========== */
@supports (-webkit-touch-callout: none) {
    body {
        -webkit-text-size-adjust: 100%;
    }
}
"""
    
    css_file = BUILD_DIR / "assets" / "css" / "style.css"
    css_file.write_text(css_content, encoding="utf-8")
    print("✅ CSS file generated")

# ============================================================
# JAVASCRIPT GENERATION
# ============================================================

def generate_js():
    """Generate JavaScript file for dark/light mode toggle"""
    js_content = """/* BG Jobs - Dark/Light Mode Toggle Script */
(function() {
    'use strict';

    const modeToggle = document.getElementById('modeToggle');
    const body = document.body;
    const STORAGE_KEY = 'bgJobsDarkMode';

    // Function to update button text and icon
    function updateToggleButton() {
        if (!modeToggle) return;
        if (body.classList.contains('dark-mode')) {
            modeToggle.innerHTML = '<span class="icon">☀️</span> Light Mode';
        } else {
            modeToggle.innerHTML = '<span class="icon">🌙</span> Dark Mode';
        }
    }

    // Function to apply saved mode
    function applySavedMode() {
        const savedMode = localStorage.getItem(STORAGE_KEY);
        if (savedMode === 'enabled') {
            body.classList.add('dark-mode');
        } else if (savedMode === 'disabled') {
            body.classList.remove('dark-mode');
        }
        // Default: light mode (no class)
        updateToggleButton();
    }

    // Function to toggle mode
    function toggleMode() {
        body.classList.toggle('dark-mode');
        if (body.classList.contains('dark-mode')) {
            localStorage.setItem(STORAGE_KEY, 'enabled');
        } else {
            localStorage.setItem(STORAGE_KEY, 'disabled');
        }
        updateToggleButton();
    }

    // Initialize
    applySavedMode();

    // Add click event listener
    if (modeToggle) {
        modeToggle.addEventListener('click', toggleMode);
    }

    // Search functionality
    const searchInput = document.getElementById('searchInput');
    const searchBtn = document.getElementById('searchBtn');
    
    function performSearch() {
        if (!searchInput) return;
        const query = searchInput.value.trim();
        if (query) {
            alert('Searching for: ' + query + '\\n(Search functionality can be integrated with backend)');
        }
    }

    if (searchBtn) {
        searchBtn.addEventListener('click', performSearch);
    }
    if (searchInput) {
        searchInput.addEventListener('keypress', function(e) {
            if (e.key === 'Enter') {
                performSearch();
            }
        });
    }

    console.log('✅ BG Jobs - Dark/Light mode initialized');
})();
"""
    
    js_file = BUILD_DIR / "assets" / "js" / "main.js"
    js_file.write_text(js_content, encoding="utf-8")
    print("✅ JavaScript file generated")

# ============================================================
# HTML PAGE GENERATION
# ============================================================

def generate_index_html():
    """Generate the main index.html page"""
    
    html_content = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes, viewport-fit=cover">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title>{SITE_NAME} | Professional Govt Job Portal – Admit Card, Result 2026</title>
    <meta name="description" content="{SITE_DESCRIPTION}">
    <meta name="keywords" content="{SITE_KEYWORDS}">
    <meta name="author" content="{SITE_AUTHOR}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="{THEME_COLOR_LIGHT}">
    
    <link rel="canonical" href="{SITE_URL}">
    
    <meta property="og:title" content="{SITE_NAME} - Professional Govt Job Portal | Admit Card & Results 2026">
    <meta property="og:description" content="{SITE_DESCRIPTION}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{SITE_URL}">
    <meta property="og:site_name" content="{SITE_NAME}">
    
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="header-top">
                <div class="header-left">
                    <h1 class="logo">
                        <a href="index.html">BG <span>Jobs</span></a>
                    </h1>
                    <button class="mode-toggle" id="modeToggle" title="Toggle Dark/Light Mode" aria-label="Dark/Light Mode Switch">
                        <span class="icon">🌙</span> Dark Mode
                    </button>
                </div>
                <div class="search-box">
                    <input type="text" id="searchInput" placeholder="Search Jobs, Results, Admit Card...">
                    <button type="button" id="searchBtn" aria-label="Search">🔍</button>
                </div>
            </div>
        </div>
        <nav class="main-nav">
            <div class="container nav-links">
                <a href="index.html" class="active">Home</a>
                <a href="jobs/index.html">Latest Jobs</a>
                <a href="results/index.html">Result</a>
                <a href="admit-card/index.html">Admit Card</a>
                <a href="answer-key/index.html">Answer Key</a>
                <a href="syllabus/index.html">Syllabus</a>
                <a href="books/index.html">Books</a>
            </div>
        </nav>
    </header>

    <div class="ticker-wrapper">
        <div class="container ticker-flex">
            <span class="ticker-label">🔥 Latest Jobs</span>
            <div class="ticker-scroll-container">
                <div class="ticker-content">
                    <a href="jobs/indian-army-ssc-tech-68-men-recruitment-2026-notification-eligibility-dates-salary.html">Indian Army SSC (Tech)-68 Notification Out</a>
                    <span class="ticker-separator">|</span>
                    <a href="jobs/mpesb-patwari-recruitment-2026-notification-out-apply-online-for-200-posts.html">MPESB Patwari Recruitment 2026 (200 Posts)</a>
                    <span class="ticker-separator">|</span>
                    <a href="jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html">Bank of India Credit Officer Admit Card 2026</a>
                    <span class="ticker-separator">|</span>
                    <a href="books/ssc-cgl-preparation-books-2026-best-recommended.html">SSC CGL Best Books 2026 - Recommended</a>
                    <span class="ticker-separator">|</span>
                    <!-- Duplicate for seamless loop -->
                    <a href="jobs/indian-army-ssc-tech-68-men-recruitment-2026-notification-eligibility-dates-salary.html">Indian Army SSC (Tech)-68 Notification Out</a>
                    <span class="ticker-separator">|</span>
                    <a href="jobs/mpesb-patwari-recruitment-2026-notification-out-apply-online-for-200-posts.html">MPESB Patwari Recruitment 2026 (200 Posts)</a>
                    <span class="ticker-separator">|</span>
                    <a href="jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html">Bank of India Credit Officer Admit Card 2026</a>
                    <span class="ticker-separator">|</span>
                    <a href="books/ssc-cgl-preparation-books-2026-best-recommended.html">SSC CGL Best Books 2026 - Recommended</a>
                </div>
            </div>
        </div>
    </div>

    <main>
        <div class="container">
            <h2 class="section-title">Explore <span>BG Jobs</span> Portal</h2>
            <div class="job-grid-container">
                
                <!-- Section 1: Latest Jobs -->
                <section class="job-card-box">
                    <div class="box-header bg-green">
                        <h2>⭐ Latest Jobs</h2>
                        <a href="jobs/index.html">View All</a>
                    </div>
                    <ul class="job-list">
                        <li><a href="jobs/indian-army-ssc-tech-68-men-recruitment-2026-notification-eligibility-dates-salary.html">Indian Army SSC (Tech)-68 Men Recruitment <span class="badge new">New</span></a></li>
                        <li><a href="jobs/mpesb-patwari-recruitment-2026-notification-out-apply-online-for-200-posts.html">MPESB Patwari Recruitment 2026 (200 Posts) <span class="badge new">New</span></a></li>
                    </ul>
                </section>

                <!-- Section 2: Admit Card -->
                <section class="job-card-box">
                    <div class="box-header bg-blue">
                        <h2>🎫 Admit Card</h2>
                        <a href="admit-card/index.html">View All</a>
                    </div>
                    <ul class="job-list">
                        <li><a href="jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html">Bank of India Credit Officer Admit Card 2026 <span class="badge hot">Hot</span></a></li>
                    </ul>
                </section>

                <!-- Section 3: Results & Exam Dates -->
                <section class="job-card-box">
                    <div class="box-header bg-red">
                        <h2>📄 Results & Exam Dates</h2>
                        <a href="results/index.html">View All</a>
                    </div>
                    <ul class="job-list">
                        <li><a href="jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html">BOI Credit Officer Exam Date 2026 <span class="badge new">New</span></a></li>
                    </ul>
                </section>

                <!-- Section 4: Books -->
                <section class="job-card-box">
                    <div class="box-header bg-purple">
                        <h2>📚 Books</h2>
                        <a href="books/index.html">View All</a>
                    </div>
                    <ul class="job-list">
                        <li><a href="books/ssc-cgl-preparation-books-2026-best-recommended.html">SSC CGL Preparation Books 2026 <span class="badge new">New</span></a></li>
                        <li><a href="books/banking-exam-books-2026-ibps-sbi-rbi-recommended.html">Banking Exam Books 2026 (IBPS/SBI/RBI) <span class="badge hot">Hot</span></a></li>
                        <li><a href="books/railway-exam-books-2026-rrb-ntpc-group-d.html">Railway Exam Books 2026 (RRB NTPC/Group D)</a></li>
                    </ul>
                </section>

            </div>
        </div>
    </main>

    <footer class="site-footer">
        <div class="container footer-content">
            <p class="copyright">&copy; 2026 {SITE_NAME}. All Rights Reserved. | Professional Govt Job Portal | Jobs | Admit Card | Results | Books</p>
        </div>
    </footer>

    <script src="assets/js/main.js"></script>
    
    <script type="application/ld+json">
    {{
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": "{SITE_NAME}",
        "url": "{SITE_URL}",
        "description": "{SITE_DESCRIPTION}",
        "inLanguage": "en"
    }}
    </script>
</body>
</html>'''
    
    index_file = BUILD_DIR / "index.html"
    index_file.write_text(html_content, encoding="utf-8")
    print("✅ index.html generated")

# ============================================================
# SAMPLE PAGES GENERATION
# ============================================================

def generate_sample_pages():
    """Generate sample pages for each section"""
    
    sample_pages = {
        "jobs": {
            "title": "Latest Jobs - BG Jobs",
            "heading": "⭐ Latest Government Jobs 2026",
            "description": "Find all latest government job notifications",
            "items": [
                {"text": "Indian Army SSC (Tech)-68 Men Recruitment 2026", "badge": "new", "url": "indian-army-ssc-tech-68-men-recruitment-2026-notification-eligibility-dates-salary.html"},
                {"text": "MPESB Patwari Recruitment 2026 (200 Posts)", "badge": "new", "url": "mpesb-patwari-recruitment-2026-notification-out-apply-online-for-200-posts.html"},
            ]
        },
        "results": {
            "title": "Results - BG Jobs",
            "heading": "📄 Latest Exam Results 2026",
            "description": "Check all government exam results",
            "items": [
                {"text": "BOI Credit Officer Exam Date 2026", "badge": "new", "url": "../jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html"},
            ]
        },
        "admit-card": {
            "title": "Admit Card - BG Jobs",
            "heading": "🎫 Download Admit Cards 2026",
            "description": "Download admit cards for all government exams",
            "items": [
                {"text": "Bank of India Credit Officer Admit Card 2026", "badge": "hot", "url": "../jobs/bank-of-india-credit-officer-admit-card-2026-out-download-call-letter.html"},
            ]
        },
        "answer-key": {
            "title": "Answer Key - BG Jobs",
            "heading": "🔑 Answer Keys 2026",
            "description": "Download answer keys for all exams",
            "items": []
        },
        "syllabus": {
            "title": "Syllabus - BG Jobs",
            "heading": "📋 Exam Syllabus 2026",
            "description": "Latest exam syllabus and patterns",
            "items": []
        },
        "books": {
            "title": "Books - BG Jobs",
            "heading": "📚 Recommended Books 2026",
            "description": "Best books for government exam preparation",
            "items": [
                {"text": "SSC CGL Preparation Books 2026", "badge": "new", "url": "ssc-cgl-preparation-books-2026-best-recommended.html"},
                {"text": "Banking Exam Books 2026 (IBPS/SBI/RBI)", "badge": "hot", "url": "banking-exam-books-2026-ibps-sbi-rbi-recommended.html"},
                {"text": "Railway Exam Books 2026 (RRB NTPC/Group D)", "badge": "", "url": "railway-exam-books-2026-rrb-ntpc-group-d.html"},
            ]
        }
    }
    
    for folder, data in sample_pages.items():
        items_html = ""
        for item in data["items"]:
            badge_html = f' <span class="badge {item["badge"]}">{item["badge"].capitalize()}</span>' if item["badge"] else ""
            items_html += f'                        <li><a href="{item["url"]}">{item["text"]}{badge_html}</a></li>\n'
        
        page_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{data["title"]}</title>
    <meta name="description" content="{data["description"]}">
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="header-top">
                <div class="header-left">
                    <h1 class="logo">
                        <a href="../index.html">BG <span>Jobs</span></a>
                    </h1>
                    <button class="mode-toggle" id="modeToggle" title="Toggle Dark/Light Mode" aria-label="Dark/Light Mode Switch">
                        <span class="icon">🌙</span> Dark Mode
                    </button>
                </div>
                <div class="search-box">
                    <input type="text" id="searchInput" placeholder="Search Jobs, Results, Admit Card...">
                    <button type="button" id="searchBtn" aria-label="Search">🔍</button>
                </div>
            </div>
        </div>
        <nav class="main-nav">
            <div class="container nav-links">
                <a href="../index.html">Home</a>
                <a href="../jobs/index.html">Latest Jobs</a>
                <a href="../results/index.html">Result</a>
                <a href="../admit-card/index.html">Admit Card</a>
                <a href="../answer-key/index.html">Answer Key</a>
                <a href="../syllabus/index.html">Syllabus</a>
                <a href="../books/index.html">Books</a>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            <h2 class="section-title">{data["heading"]}</h2>
            <div class="job-grid-container">
                <section class="job-card-box" style="grid-column: 1 / -1;">
                    <div class="box-header bg-green">
                        <h2>{data["heading"]}</h2>
                    </div>
                    <ul class="job-list">
{items_html}
                    </ul>
                </section>
            </div>
        </div>
    </main>

    <footer class="site-footer">
        <div class="container footer-content">
            <p class="copyright">&copy; 2026 {SITE_NAME}. All Rights Reserved.</p>
        </div>
    </footer>

    <script src="../assets/js/main.js"></script>
</body>
</html>'''
        
        page_file = BUILD_DIR / folder / "index.html"
        page_file.write_text(page_html, encoding="utf-8")
        print(f"✅ {folder}/index.html generated")

# ============================================================
# .NOJEKYLL & CNAME GENERATION
# ============================================================

def generate_github_config():
    """Generate GitHub Pages configuration files"""
    
    # .nojekyll file (disable Jekyll processing)
    nojekyll_file = BUILD_DIR / ".nojekyll"
    nojekyll_file.write_text("")
    print("✅ .nojekyll generated")
    
    # CNAME file (custom domain - optional)
    # cname_file = BUILD_DIR / "CNAME"
    # cname_file.write_text("yourdomain.com")
    
    # 404 page
    html_404 = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Not Found - BG Jobs</title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <main>
        <div class="container" style="text-align: center; padding: 100px 20px;">
            <h1 style="font-size: 4rem; color: #ff6b00;">404</h1>
            <h2>Page Not Found</h2>
            <p style="margin: 20px 0;">The page you are looking for might have been removed or is temporarily unavailable.</p>
            <a href="index.html" style="background: #ff6b00; color: #0a0a0a; padding: 12px 30px; border-radius: 50px; font-weight: 700; display: inline-block; margin-top: 20px;">Go to Homepage</a>
        </div>
    </main>
    <script src="assets/js/main.js"></script>
</body>
</html>'''
    
    file_404 = BUILD_DIR / "404.html"
    file_404.write_text(html_404, encoding="utf-8")
    print("✅ 404.html generated")

# ============================================================
# MAIN BUILD FUNCTION
# ============================================================

def build():
    """Main build function"""
    print("=" * 60)
    print(f"🚀 Building {SITE_NAME} - Professional Govt Job Portal")
    print(f"📅 Build Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # Clean build directory
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
        print("🧹 Cleaned build directory")
    
    # Setup
    setup_directories()
    generate_css()
    generate_js()
    generate_index_html()
    generate_sample_pages()
    generate_github_config()
    
    print("=" * 60)
    print("✅ BUILD COMPLETE!")
    print(f"📁 Output directory: {BUILD_DIR.absolute()}")
    print("=" * 60)
    print("\n📋 To deploy to GitHub Pages:")
    print("   1. Push the contents of '_build' folder to your GitHub repository")
    print("   2. Go to Settings > Pages > Source: Deploy from branch")
    print("   3. Select branch (main/master) and folder (root)")
    print("   4. Click Save")
    print("\n🌐 Your site will be live at: " + SITE_URL)

# ============================================================
# RUN BUILD
# ============================================================

if __name__ == "__main__":
    build()
